// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ampujoodbjcjoydoumjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtcHVqb29kYmpjam95ZG91bWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTEwOTYsImV4cCI6MjA3MjIyNzA5Nn0.WSRdSQTeyOCGjIwIwCABbsd1bSx5nHtCLRco-4VpOoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});